acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.ulogin, name="login"),
    path('logout/', views.ulogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass"),
    path('delete/', views.delete, name="delete"),
]

book/urls.py
from django.urls import path
from . import views

app_name="book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls')),
    path('album/', include('album.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name="vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('delete/<tpk>', views.delete, name="delete"),
    path('create/', views.create, name="create")
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.

class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")

    def __str__(self):
        return self.subject

class Choice(models.Model):
    top = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.top}_{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice

# Create your views here.

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        cn = request.POST.get("cname")
        cc = request.POST.get("ccom")
        t = Topic(subject=s, content=c, maker=request.user)
        t.save()
        for name, com in zip(cn,cc):
            Choice(top=t, name=name, comment=com).save()
        return redirect('vote:index')

    return render(request, "vote/create.html")


def delete(request, tpk):
    t = Topic.objects.get(id=tpk)
    if request.user == t.maker:
        t.delete()
    else:
        pass #마지막 경고!
    
    return redirect('vote:index')

def cancel(request,tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    t.voter.remove(u)
    u.choice_set.get(top=t).choicer.remove(u)
    return redirect("vote:detail", tpk)

def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect("vote:detail", tpk)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t":t,
        "cset":c
    }
    return render(request, "vote/detail.html", context)
def index(request):
    t = Topic.objects.all()
    context = {
        "tset" : t
    }
    return render(request, "vote/index.html", context)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>토픽생성</b></h1>

    <form method="post">
        {% csrf_token %}
        <input type="text" name="sub" placeholder="INPUT SUBJECT" class="form-control mt-5">
        <input type="text" value="{{user}}" disabled class="form-control mt-3 mb-3">
        <textarea class="form-control" name="con" style="height: 200px;" placeholder="INPUT CONTENT"></textarea>

        <div class="text-end mt-4">
            <button type="button" onclick="makecho()" class="btn btn-dark">보기생성</button>
            <button class="btn btn-dark">토픽생성</button>
        </div>

        <div id="here" class="row mt-5"></div>
    </form>

    <script>
        function makecho(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-sm-4");
            n.innerHTML = "<input type='text' name='cname' placeholder='INPUT NAME' class='form-control'>\
            <textarea class='form-control mt-3 mb-5' name='ccom' placeholder='INPUT COMMENT'></textarea>";
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}
    
    <h1><b>{{ t.subject }}</b></h1>

    <div class="text-end">
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#post">
            ✨
        </button>
    </div>

    <div class="row mt-4">
        <div class="col-sm-9">
            <textarea class="form-control" style="height:250px" disabled>{{ t.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ t.maker.getpic }}" width="100%">
            <div class="mt-3 text-center">
                <h5>made by {{ t.maker }}</h5>
            </div>
        </div>

    </div>

    <hr>

    {% if user in t.voter.all %}
    
        <div class="row mt-5">
            {% for i in cset %}
                <div class="col-sm-4">
                    <label class="form-check-label">
                        <h4><b>{{ i.name }}</b></h4>
                    </label>
                    <div class="progress mt-3 mb-3" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%">{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%</div>
                    </div>
                    <textarea class="form-control mt-3" style="height:100px;" disabled>{{ i.comment }}</textarea>
                </div>
            {% endfor %}
        </div>
        <div class="text-end mt-4">
            <a href="{% url 'vote:cancel' t.id %}" class="btn btn-danger">무르기</a>
        </div>
    {% else %}

        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col sm-4">
                        <input type="radio" {% if forloop.first %} checked {% endif %} name="cho" value="{{i.id}}" class="form-check-input">
                        <label class="form-check-label">
                            <h4><b>{{ i.name }}</b></h4>
                        </label>
                        <textarea class="form-control mt-3" style="height:100px;" disabled>{{ i.comment }}</textarea>
                    </div>
                {% endfor %}
            </div>   
            <div class="text-end mt-4">
                <button class="btn btn-dark">투표하기</button></a>
            </div>
    {% endif %}
        
    </form>

    <!-- 모달창 -->
    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="post" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">즐겨찾기 추가 알림창</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="text-end">
                            <div class="text-end">
                                <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                                <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                            </div>
                            <textarea class="form-control" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                            <input type="hidden" name="sname" value="[VOTE] {{ b.subject }}">
                            <input tupe="hidden" name="surl" value="{{ request.path }}">
                        </div>                   
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">창 닫기</button>
                        <button type="button" class="btn btn-warning">즐겨찾기 추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>투표소</b></h1>
    
    <div class="text-end">
        <a href="{% url 'vote:create' %}" type="button" class="btn btn=dark btn-lg">+TOPIC</a>
    </div>
    
    <div class="row">
        {%for i in tset%}
            <div class="col-sm-4">
                <div class="card text-center">
                    <img src="{{ i.maker.getpic }}" class="card-img-top" alt="...">
                    <div class="card-body" {% if user in i.voter.all %} style="background-color: rgb(250, 235, 235);" {% endif %}>
                        <h5 class="card-title"><b>{{ i.subject }}</b></h5>
                        <p class="card-text">{{ i.content|truncatewords:8 }}</p>
                        <a href="{% url 'vote:detail' i.id %}" class="btn btn-outline-dark">
                            {% if user in i.voter.all %}결과보기{% else %} 투표하기 {% endif %}
                        </a>
                       
                        {% if i.maker == user %}
                            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#e{{forloop.counter}}">
                                삭제하기
                            </button>
                        {% endif %}
                    </div>
                </div>        
            </div>
        {% endfor %}

    </div>


    {% for i in tset %}
     <!-- Modal -->
        {% if user == i.maker %}
            <div class="modal fade" id="e{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel"><b>{{ i.subject }}</b>토픽 삭제 알림창</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <mark><b>{{ i.voter.count }}</b></mark>명이 참여한 투표입니다. 그대로 삭제하시겠습니까?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">창 닫기</button>
                            <a href="{% url 'vote:delete' i.id %}" type="button" class="btn btn-primary">토픽 삭제하기</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}


{% endblock %}