acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.ulogin, name="login"),
    path('logout/', views.ulogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass"),
    path('delete/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls')),
    path('album/', include('album.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    comment = models.TextField(blank=True)
    age = models.IntegerField(default=0)
    point = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y")

    def getpic(self):
        if self.pic:
            return self.pic.url
            
        return "/media/noimage.png"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.contrib.auth.hashers import check_password
from django.contrib import messages

# Create your views here.

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomment")
        ua = request.POST.get("uage")
        upic = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, comment=uc, age=ua, upic=upic)
            return redirect("acc:login")
        except:
            pass #마지막
    return render(request, "acc/signup.html")

def delete(request):
    u = request.user
    cp = request.POST.get("cpass")
    if check_password(cp, u.password):
        u.pic.delete()
        u.delete()
        return redirect("acc:index")
    return redirect("acc:index")

def chpass(request):
    if request.method == "POST":
        u = request.user
        cp = request.POST.get("cpass")
        if check_password(cp, u.password):     
            np = request.POST.get("npass")
            u.set_password(np)
            u.save()
            return redirect("login")
        else: #마지막
            pass
    return render(request, "acc/chpass.html")

def update(request):
    if request.method == "POST":
        u= request.user
        um = request.POST.get("umail")
        up = request.FILES.get("upic")
        uc = request.POST.get("ucomment")
        if up:
            u.pic.delete()
            u.pic = up
        u.email, u.comment = um, uc
        u.save
        return redirect("acc:profile")
        
    return render(request, "acc/update.html")

def profile(request):
    return render(request, "acc/profile.html")

def signup(request): 
    if request.user.is_authenticated:
        return redirect("acc:index")
    
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        try:
            User.objects.create_user(username=un, password=up)
            return redirect("acc:login")
        except:
            pass
    return render(request, "acc/signup.html")

def ulogout(request):
    logout(request)
    messages.success(request, "로그아웃 되었습니다.")
    return redirect("acc:index")

def ulogin(request):

    if request.user.is_authenticated:
        return redirect("acc:index")

    if request.method =="POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username = un, password = up)
        if u: 
            login(request, u) 
            messages.success(request, f"{u}님 환영합니다!" )
            return redirect("acc:index")
        else:
            messages.info(request, "계정 정보가 일치하지 않습니다.")
    return render(request, "acc/login.html")


def index(request):
    return render(request, "acc/index.html")

templates/acc/chpass.html
{% extends 'base.html' %}

{% block con %}

<h1>CHANGE PASSWORD</h1>

<form method="post">
    {% csrf_token %}
    <input type ="password" name = "cpass" placeholder="INPUT CURRENT PASSWORD"><br><br>
    <input type ="password" name = "npass" placeholder="INPUT NEW PASSWORD"><br><br>
    <button>CHANGE</button>
</form>

{% endblock %}

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">WELCOME TO MY WEBSITE!</h1>
        <p class="col-md-8 fs-4">Hello everyone! My first django project 💥 </p>
    </div>
</div>

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block con %}

    <h1><b>LOGIN PAGE</b></h1>

    <form method="post">
        {% csrf_token %}
        <input type="text" name="uname" class="form-control mt-5" placeholder="INPUT USERNAME">
        <input type="password" name="upass" class="form-control mt-3" placeholder="INPUT PASSWORD">

        <div class="text-end mt-4">
            <button class="btn btn-dark btn-lg">LOGIN</button>
        </div>
    </form>

{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}

{% block con %}

<div class="container mt-5 mb-5">
    <h1><b>{{ user }}'s PROFILE</b></h1>

    <div class="row">
        <div class="col-sm-7 text-center" style="margin: auto;">
            <img src="{{ user.getpic }}" class="rounded-circle" width="80%">
        </div>
        <div class="col-sm-5">

            <label class="form-label mt-5">USERNAME</label>
            <input type="text" value = "{{ user }}"disabled class="form-control">
    
            <label class="form-label mt-4">POINT</label>
            <input type="text" value="{{user.point}}"disabled class="form-control">
    
            <label class="form-label mt-4">EMAIL</label>
            <input type="text" value="{{user.email}}"disabled class="form-control">

            <label class="form-label mt-4">COMMENT</label>
            <textarea class="form-control" value="{{user.comment}}"disabled></textarea>
        </div>
    </div>

    <div class="mt-5 text-end">
        <a href="{% url 'acc:update' %}" class="btn btn-dark btn-lg">정보수정</a>
        <!-- modal trigger button -->
        <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
            계정삭제
        </button>
    </div>
    
</div>

<!-- Modal -->
<form method ="post" action="{% url 'acc:delete' %}">
    {% csrf_token %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">계정 삭제 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <label class="form-label">패스워드 확인</label>
                    <input type="password" class="form-control" placeholder="INPUT PASSWORD">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-danger">삭제</button></a>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block con %}

    <form method ="post" enctype="multipart/form-data" name="createForm">
        {% csrf_token %}
        <h1><b>SIGNUP PAGE</b></h1>

        <label class="form-label mt-5">USERNAME</label>
        <input type="text" name="uname" class="form-control">

        <label class="form-label mt-4">PASSWORD</label>
        <input type="password" name="upass" class="form-control">

        <label class="form-label mt-4">CHECK PASSWORD</label>
        <input type="password" name="chpass" class="form-control">

        <label class="form-label mt-4">AGE</label>
        <input type="number" name="uage" class="form-control">

        <label class="form-label mt-4">USERPIC</label>
        <input type="file" name="upic" class="form-control">

        <label class="form-label mt-4">COMMENT</label>
        <textarea class="form-control" name="ucomment"></textarea> 

        <div class="text-end mt-4">
            <button class="btn btn-dark btn-lg" type="button" onclick="check()">회원가입</button>
        </div>
    </form>

    <script>
        function check(){
            cf = document.createForm;
            if(!cf.uname.value){
                alert("USERNAME을 입력하세요");
            
            }else if(!cf.upass.value){
                alert("PASSWROD를 입력하세요");
            }else if(cf.upass.value != cf.chpass.value){
                alert("PASSWORD가 일치하지 않습니다. ");
            }else if(cf.ucomment.value.length < 10){
                alert("최소 10자 이상은 입력해주시기 바랍니다.");
            }else{
                cf.submit();
            }
            
        }
    </script>


{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}

{% block con %}

<h1><b>UPDATE PAGE</b></h1>

<form method ="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- username 은 변경불가하도록 disabled 유지 -->
    <label class="form-label mt-5">USERNAME</label>
    <input type="text" disabled value="{{user}}" class="form-control">

    <label class="form-label mt-4">EMAIL</label>
    <input type="text" value="{{user.email}}" name="umail" class="form-control">

    <label class="form-label mt-4">USERPIC</label>
    <input type="file" name="upic" class="form-control">

    <label class="form-label mt-4">COMMENT</label>
    <textarea class="form-control"name="ucomment">{{ user.comment }}</textarea> 

    <div class="text-end mt-4">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
            패스워드변경
        </button>
        <button class="btn btn-dark btn-lg">수정완료</button>
    </div>

</form>



<!-- Modal -->
<form method="post" action="{% url 'acc:chpass' %}">
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel"><b>패스워드 변경창</b></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="password" name="cpass" placeholder="CURRENT PASSWORD" class="form-control">
                    <input type="password" name="npass" placeholder="NEW PASSWORD" class="form-control mt-3">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-primary">변경</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}