acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.ulogin, name="login"),
    path('logout/', views.ulogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass"),
    path('delete/', views.delete, name="delete"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey"),
]

book/urls.py
from django.urls import path
from . import views

app_name="book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls')),
    path('album/', include('album.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
from django.utils import timezone

# Create your models here.

class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField(default=timezone.now)
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return self.subject

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    
    def __str__(self):
        return f"{self.board}_{self.replyer}님의 댓글" 

board/views.py
from django.shortcuts import render, redirect
from .models import Board
from django.core.paginator import Paginator

# Create your views here.

def unlikey(request, bpk): 
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail", bpk)

def likey(request, bpk): 
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail", bpk)

def index(request):
    # print(dir(request.user.is_authenticated))
    # print(dir(request.user.is_anonymous))  
    kw = request.GET.get("kw","")  
    cate = request.GET.get("cate","")
    page = request.GET.get("page", 1)
    if kw :
        if cate == "sub" :
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri": 
            try :
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except : 
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
    else :   
        b = Board.objects.all()

    b = b.order_by("-pubdate")   #최신글이 앞으로, 반대는 pubdate

    pag = Paginator(b, 3)
    obj = pag.get_page(page)
    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw,
    }
    
    
    return render(request, "board/index.html", context)

def create(request):
    if request.method =="POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, content=c, writer=request.user).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def delete(reqeust, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == reqeust.user:
            b.delete()
    else:
        pass #경고메시지
    return redirect("board:index")

def detail(request, bpk):

    if request.user.is_anonymous:
        return redirect("acc:login")

    b= Board.objects.get(id=bpk)
    context = {
        "b" : b
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}

{% block con %}

    <h1><b>게시글 생성</b></h1>
    <form method="post">
        {% csrf_token %}
        <input class="form-control mt-5" name = "sub" placeholder="INPUT SUBJECT">
        <input class="form-control mt-4 mb-4" value="{{ user }}" disabled>
        <textarea class="form-control" name = "con" style="height: 250px;" placeholder="INPUT CONTENT"></textarea>

        <div class="text-end mt-4">
            <button class="btn btn-dark">생성하기</button>
        </div>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}

    <h1><b>{{ b.subject }}</b></h1>
 
    <div class="text-end">
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#post">
            ✨
        </button>
    </div>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 250px;" disabled>{{b.content}}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h4>written by <b>{{ b.writer }}</b></h4>
            </div>
            <div class="text-end mt-2">
                {{b.pubdate|date:'Y년 m월 d일 / H:i'}}
            </div> 
        </div>
    </div>

    <div class="text-end mt-4">
        <a href="{% url 'board:index' %}" class="btn btn-dark">메인</a>
        {% if user in b.likey.all %}
            <a href="{% url 'board:unlikey' b.id %}" class="btn btn-primary">좋아요 취소</a>
        {% else %}
            <a href="{% url 'board:likey' b.id %}" class="btn btn-primary">좋아요</a>
        {% endif %}
        

        {% if user == b.writer %}
            <a href="#" class="btn btn-secondary">수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                삭제
            </button>
        {% endif %}
    </div>

    <!-- post 모달창 -->
    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="post" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">즐겨찾기 추가 알림창</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="text-end">
                            <div class="text-end">
                                <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                                <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                            </div>
                            <textarea class="form-control" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                            <input type="hidden" name="sname" value="[BOARD] {{ b.subject }}">
                            <input tupe="hidden" name="surl" value="{{ request.path }}">
                        </div>                   
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">창 닫기</button>
                        <button type="button" class="btn btn-warning">즐겨찾기 추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <!-- 삭제모달창 -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">게시글 삭제 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}" type="button" class="btn btn-danger">삭제하기</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}
    <h1><b>SH BOARD</b></h1>

    <div class="text-end">
        <a class="btn btn-dark" href="{% url 'board:create' %}">WRITE</a>
    </div>

    <table class="table table-hover mt-4">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">WRITER</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% for i in bset %}
                <tr>
                    <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                    <td><a href="{% url 'board:detail' i.id %}" class="sub">{{ i.subject }}</a></td>
                    <td>{{ i.writer }}</td>
                    <td>{{ i.content|truncatewords:6 }}</td>
                    <td>{{ i.likey.count }}</td>
                </tr>
            {% empty %}
                <tr class="text-center">
                    <th colspan="5"><h4>{% if kw %} 검색결과가 존재하지 않습니다 😋 {% else %} 첫번째 게시글을 작성해주세요 💦 {% endif %}</h4></th>
                </tr>
            {% endfor %}

        </tbody>
    </table>


    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}

            {% for i in bset.paginator.page_range %}
                {% if bset.number|add:3 >= i and i >= bset.number|sub:3 %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
        </ul>
    </nav>

    <form>
        <div class="row">
            <div class="col-sm-2">
                <select class="form-select" name="cate">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-8">
                <input type="text" name="kw" value="{{kw}}" class="form-control" placeholder="검색어를 입력해주세요">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-dark" style="width: 100%;">검색</button>
            </div>
            <div class="col-sm-1">
                <a class="btn btn-secondary" href="{% url 'board:index' %}" style="width: 100%;">초기화</a>
            </div>
        </div>
    </form>

  

    <style>
        .sub {
            text-decoration: none;
            color: rgb(41, 39, 39);
            font-weight: bold;
        }
        .sub:hover{
            color:rgb(255, 0, 0);
        }
    </style>


{% endblock %}